import { DatabaseState } from '../types';

export const initialDatabase: DatabaseState = {
  vehicles: [
    {
      id: 'veh-1',
      plateNumber: 'AA-BC-328',
      brandModel: 'Toyota Yaris 1.5 Hybrid',
      year: 2022,
      category: 'B',
      transmission: 'Automata',
      currentKm: 48520,
      status: 'in_use',
      motDate: '2026-11-15',
      motReminderDays: 30,
      dualPedals: true,
      currentInstructorId: 'inst-1',
      checkoutTime: '2026-09-21T08:00',
      checkoutKm: 48490,
      notes: 'Oktatói pótfék és gázpedál, kiegészítő visszapillantó tükrökkel.',
    },
    {
      id: 'veh-2',
      plateNumber: 'AA-DL-512',
      brandModel: 'Škoda Fabia 1.0 TSI',
      year: 2021,
      category: 'B',
      transmission: 'Manuális',
      currentKm: 72150,
      status: 'active',
      motDate: '2026-10-02', // Hamarosan lejár! (< 14 nap)
      motReminderDays: 30,
      dualPedals: true,
      notes: 'Kiváló állapotban, de az esedékes műszaki vizsga időpontja sürgető!',
    },
    {
      id: 'veh-3',
      plateNumber: 'SZX-419',
      brandModel: 'Suzuki Swift 1.2 Dualjet',
      year: 2019,
      category: 'B',
      transmission: 'Manuális',
      currentKm: 118400,
      status: 'service',
      motDate: '2027-04-10',
      motReminderDays: 30,
      dualPedals: true,
      notes: 'Szervizben: kuplung szett csere és fékbetét felújítás folyamatban.',
    },
    {
      id: 'veh-4',
      plateNumber: 'RLN-883',
      brandModel: 'Opel Astra K 1.4 Turbo',
      year: 2018,
      category: 'B',
      transmission: 'Manuális',
      currentKm: 142000,
      status: 'deregistered',
      motDate: '2026-06-20',
      motReminderDays: 30,
      dualPedals: true,
      deregistrationDate: '2026-07-01',
      deregistrationReason: 'Nyári szüneteltetés / motorfelújítás előkészítése.',
      notes: 'Forgalomból ideiglenesen kivonva.',
    },
    {
      id: 'veh-5',
      plateNumber: 'AA-MO-104',
      brandModel: 'Yamaha MT-07 ABS',
      year: 2023,
      category: 'A',
      transmission: 'Manuális',
      currentKm: 14250,
      status: 'active',
      motDate: '2027-05-18',
      motReminderDays: 30,
      dualPedals: false,
      notes: 'Motorkerékpár oktatás, bukócsővel és rádiós adóvevő készlettel.',
    },
    {
      id: 'veh-6',
      plateNumber: 'MAN-720',
      brandModel: 'MAN TGL 12.220',
      year: 2017,
      category: 'C',
      transmission: 'Manuális',
      currentKm: 310500,
      status: 'active',
      motDate: '2026-12-05',
      motReminderDays: 45,
      dualPedals: true,
      notes: 'C kategóriás tehergépkocsi, tachográffal felszerelve.',
    },
  ],
  instructors: [
    {
      id: 'inst-1',
      name: 'Kiss László',
      phone: '+36 30 452 8192',
      email: 'laszlo.kiss@autosuli.hu',
      licenseNumber: 'OKT-2015-8841',
      categories: ['B'],
      preferredVehicleId: 'veh-1',
      status: 'active',
      color: '#3b82f6', // blue
      notes: 'Vezető B kategóriás oktató, 15 év szakmai tapasztalat.',
    },
    {
      id: 'inst-2',
      name: 'Tóth Andrea',
      phone: '+36 70 882 1450',
      email: 'andrea.toth@autosuli.hu',
      licenseNumber: 'OKT-2018-9122',
      categories: ['B'],
      preferredVehicleId: 'veh-2',
      status: 'active',
      color: '#10b981', // emerald
      notes: 'Türelmes, kezdő tanulók specialistája.',
    },
    {
      id: 'inst-3',
      name: 'Kovács István',
      phone: '+36 20 311 9044',
      email: 'istvan.kovacs@autosuli.hu',
      licenseNumber: 'OKT-2011-4029',
      categories: ['A', 'B', 'C'],
      preferredVehicleId: 'veh-5',
      status: 'active',
      color: '#f59e0b', // amber
      notes: 'Motorkerékpár és nehézgépjármű oktató.',
    },
  ],
  students: [
    {
      id: 'stud-1',
      name: 'Molnár Bence',
      phone: '+36 30 119 4502',
      email: 'bence.molnar@gmail.com',
      category: 'B',
      instructorId: 'inst-1',
      theoryExamStatus: 'Sikeres',
      medicalExamExpiry: '2026-10-10', // Hamarosan lejár orvosi!
      completedHours: 28,
      requiredHours: 30,
      completedKm: 540,
      requiredKm: 580,
      paymentStatus: 'Rendezve',
      status: 'exam_ready',
      notes: 'Forgalmi vizsgára vár, már csak 2 óra és 40 km hiányzik.',
    },
    {
      id: 'stud-2',
      name: 'Horváth Dóra',
      phone: '+36 70 941 2280',
      email: 'dora.horvath@freemail.hu',
      category: 'B',
      instructorId: 'inst-2',
      theoryExamStatus: 'Sikeres',
      medicalExamExpiry: '2027-08-15',
      completedHours: 14,
      requiredHours: 30,
      completedKm: 260,
      requiredKm: 580,
      paymentStatus: 'Rendezve',
      status: 'active',
      notes: 'Városi vezetés és parkolási feladatok gyakorlása.',
    },
    {
      id: 'stud-3',
      name: 'Varga Zoltán',
      phone: '+36 20 774 1902',
      email: 'zoltan.varga@infomail.hu',
      category: 'C',
      instructorId: 'inst-3',
      theoryExamStatus: 'Sikeres',
      medicalExamExpiry: '2027-02-28',
      completedHours: 18,
      requiredHours: 30,
      completedKm: 320,
      requiredKm: 580,
      paymentStatus: 'Részletben',
      status: 'active',
      notes: 'Teherautó C kategóriás tanfolyam, 2. részlet befizetve.',
    },
    {
      id: 'stud-4',
      name: 'Németh Balázs',
      phone: '+36 30 665 9931',
      email: 'balazs.nemeth@mailbox.hu',
      category: 'A',
      instructorId: 'inst-3',
      theoryExamStatus: 'Sikeres',
      medicalExamExpiry: '2027-06-12',
      completedHours: 22,
      requiredHours: 30,
      completedKm: 420,
      requiredKm: 580,
      paymentStatus: 'Rendezve',
      status: 'active',
      notes: 'Rutinpálya sikeresen teljesítve, országúti szakasz folyamatban.',
    },
  ],
  lessons: [
    {
      id: 'les-1',
      date: '2026-09-21',
      startTime: '08:00',
      endTime: '09:30',
      instructorId: 'inst-1',
      studentId: 'stud-1',
      vehicleId: 'veh-1',
      lessonType: 'Városi vezetés',
      status: 'completed',
      kmStart: 48490,
      kmEnd: 48520,
      notes: 'Csúcsforgalmi körforgalmak és sávváltások gyakorlása.',
    },
    {
      id: 'les-2',
      date: '2026-09-21',
      startTime: '10:00',
      endTime: '11:30',
      instructorId: 'inst-1',
      studentId: 'stud-1',
      vehicleId: 'veh-1',
      lessonType: 'Gyakorló óra',
      status: 'scheduled',
      notes: 'Vizsga útvonalak bejárása.',
    },
    {
      id: 'les-3',
      date: '2026-09-21',
      startTime: '14:00',
      endTime: '15:30',
      instructorId: 'inst-2',
      studentId: 'stud-2',
      vehicleId: 'veh-2',
      lessonType: 'Városi vezetés',
      status: 'scheduled',
      notes: 'Párhuzamos és merőleges parkolási technikák.',
    },
    {
      id: 'les-4',
      date: '2026-09-22',
      startTime: '09:00',
      endTime: '11:00',
      instructorId: 'inst-3',
      studentId: 'stud-4',
      vehicleId: 'veh-5',
      lessonType: 'Országúti vezetés',
      status: 'scheduled',
      notes: 'Motoros kanyartechnika és dinamikus fékezés.',
    },
    {
      id: 'les-5',
      date: '2026-09-23',
      startTime: '13:00',
      endTime: '15:00',
      instructorId: 'inst-3',
      studentId: 'stud-3',
      vehicleId: 'veh-6',
      lessonType: 'Városi vezetés',
      status: 'scheduled',
      notes: 'MAN teherautó szűk utcai kanyarodási ívek.',
    },
  ],
  maintenance: [
    {
      id: 'maint-1',
      vehicleId: 'veh-3',
      date: '2026-09-18',
      type: 'Kuplung/Váltó',
      description: 'Kuplungtárcsa és kinyomócsapágy csere, lendkerék ellenőrzés.',
      workshop: 'Profi Autószerviz Kft.',
      cost: 145000,
      kmAtService: 118400,
      status: 'Folyamatban',
    },
    {
      id: 'maint-2',
      vehicleId: 'veh-2',
      date: '2026-08-10',
      type: 'Olajcsere',
      description: 'Motorolaj 5W-30, olajszűrő, levegőszűrő és pollenszűrő csere.',
      workshop: 'Márkaszerviz Flottapartner',
      cost: 42000,
      kmAtService: 70000,
      status: 'Befejezett',
    },
    {
      id: 'maint-3',
      vehicleId: 'veh-1',
      date: '2026-07-22',
      type: 'Pótpedál karbantartás',
      description: 'Oktatói pótfék bowden feszesítés, vizsga előtti ellenőrzés.',
      workshop: 'Pedál-Special Kft.',
      cost: 25000,
      kmAtService: 44100,
      status: 'Befejezett',
    },
  ],
  fuelLogs: [
    {
      id: 'fuel-1',
      vehicleId: 'veh-1',
      instructorId: 'inst-1',
      date: '2026-09-19',
      currentKm: 48450,
      liters: 32.5,
      totalCost: 19825,
      fuelType: 'Benzin (E10)',
      fullTank: true,
      calculatedLitersPer100Km: 4.8,
    },
    {
      id: 'fuel-2',
      vehicleId: 'veh-2',
      instructorId: 'inst-2',
      date: '2026-09-16',
      currentKm: 72010,
      liters: 41.0,
      totalCost: 25010,
      fuelType: 'Benzin (E10)',
      fullTank: true,
      calculatedLitersPer100Km: 5.6,
    },
    {
      id: 'fuel-3',
      vehicleId: 'veh-6',
      instructorId: 'inst-3',
      date: '2026-09-12',
      currentKm: 310200,
      liters: 120.0,
      totalCost: 75600,
      fuelType: 'Gázolaj (B7)',
      fullTank: true,
      calculatedLitersPer100Km: 21.5,
    },
  ],
  assignmentLogs: [
    {
      id: 'asg-1',
      vehicleId: 'veh-1',
      instructorId: 'inst-1',
      checkedOutAt: '2026-09-21T08:00',
      startKm: 48490,
      purpose: 'Délelőtti B kategóriás vezetési órák (Molnár Bence).',
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      title: 'Műszaki vizsga hamarosan esedékes',
      message: 'AA-DL-512 (Škoda Fabia) műszaki vizsgája 2026-10-02 napon lejár!',
      type: 'mot_due',
      date: '2026-09-20',
      sentAsDesktop: true,
      sentAsEmail: false,
    },
    {
      id: 'notif-2',
      title: 'Orvosi alkalmassági lejárat figyelmeztetés',
      message: 'Molnár Bence tanuló orvosi igazolása 2026-10-10 napon lejár a forgalmi vizsga előtt!',
      type: 'medical_due',
      date: '2026-09-20',
      sentAsDesktop: false,
      sentAsEmail: true,
    },
  ],
  schoolCompany: {
    schoolName: 'AutoSuli Gépjárművezető-képző Iskola',
    companyName: 'AutoSuli Képzési és Szolgáltató Kft.',
    registrationNumber: '01-09-987654',
    taxNumber: '12345678-2-41',
    accreditationNumber: 'KAV/2021/B-0042',
    address: '1117 Budapest, Október huszonharmadika u. 8-10.',
    phone: '+36 1 456 7890',
    email: 'iroda@autosuli-kepzes.hu',
    website: 'https://autosuli-kepzes.hu',
    representativeName: 'Kovács Zoltán (Iskolavezető)',
    bankAccountNumber: '11705008-20456123-00000000 (OTP Bank)',
    termsText:
      'A Képző Szerv vállalja, hogy a választott kategóriás elméleti és gyakorlati képzést a hatályos 24/2005. (IV. 21.) GKM rendelet előírásainak megfelelően biztosítja. A Tanuló kijelenti, hogy az orvosi alkalmassági igazolással rendelkezik, a Képzési Szerződés feltételeit és a házirendet maradéktalanul elfogadja. Részletfizetés esetén a pótdíjak és vizsgadíjak az esedékességkor fizetendők.',
  },
  courseOffers: [
    {
      id: 'course-b',
      name: 'B Kategóriás Személygépkocsi-vezetői Tanfolyam',
      category: 'B',
      theoryHours: 28,
      practiceHours: 30,
      requiredKm: 580,
      basePrice: 345000,
      examFee: 26000,
      description: 'Komplett e-learning vagy tantermi elmélet + kötelező 30 tanóra (580 km) gyakorlati vezetés modern autókkal.',
      paymentOptions: ['Egyösszegben (5% kedvezmény)', '3 részletben kamatmentesen', 'Gyakorlati óránkénti elszámolás'],
    },
    {
      id: 'course-a',
      name: 'A Kategóriás Nagymotor Tanfolyam',
      category: 'A',
      theoryHours: 22,
      practiceHours: 26,
      requiredKm: 390,
      basePrice: 285000,
      examFee: 24000,
      description: 'Korlátlan motorkerékpár vezetői képzés tanpályás alapoktatással és forgalmi felkészítéssel.',
      paymentOptions: ['Egyösszegben', '2 részletben'],
    },
    {
      id: 'course-c',
      name: 'C Kategóriás Tehergépkocsi-vezetői Képzés',
      category: 'C',
      theoryHours: 30,
      practiceHours: 30,
      requiredKm: 580,
      basePrice: 420000,
      examFee: 32000,
      description: 'Profi hivatásos teherautó vezetői képzés saját korszerű MAN oktatójárművünkön.',
      paymentOptions: ['Egyösszegben', 'Céges átutalással (30 nap)', '3 részletben'],
    },
    {
      id: 'course-ce',
      name: 'CE Kategóriás Nehézpótkocsi Képzés',
      category: 'CE',
      theoryHours: 14,
      practiceHours: 16,
      requiredKm: 300,
      basePrice: 260000,
      examFee: 28000,
      description: 'Kamion és nehézpótkocsi szerelvény képzés C kategóriás jogosítvánnyal rendelkezőknek.',
      paymentOptions: ['Egyösszegben', 'Céges elszámolással'],
    },
  ],
  courseRegistrations: [
    {
      id: 'reg-1',
      contractNumber: 'AS-2026/09-001',
      date: '2026-09-18',
      courseId: 'course-b',
      courseName: 'B Kategóriás Személygépkocsi-vezetői Tanfolyam',
      category: 'B',
      studentName: 'Horváth Tamás',
      birthName: 'Horváth Tamás',
      mothersName: 'Szabó Erzsébet',
      birthPlace: 'Budapest',
      birthDate: '2004-06-15',
      idCardNumber: '123456AB',
      address: '1112 Budapest, Budaörsi út 45.',
      phone: '+36 30 789 1234',
      email: 'horvath.tamas@gmail.com',
      medicalExamExpiry: '2027-08-30',
      hasExistingLicense: 'AM (Segédmotor)',
      instructorId: 'inst-1',
      instructorName: 'Kovács Zoltán',
      paymentPlan: '3 részletben kamatmentesen',
      totalFee: 371000,
      initialDeposit: 120000,
      studentSignatureSvg: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M 20 40 Q 50 10 90 35 T 160 25" stroke="%231e293b" stroke-width="2" fill="none"/></svg>',
      representativeSignatureSvg: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M 20 30 Q 60 50 100 20 T 170 35" stroke="%230284c7" stroke-width="2" fill="none"/></svg>',
      signedAt: '2026-09-18T14:30:00.000Z',
      status: 'signed',
      syncedToStudents: true,
      studentId: 'stud-2',
      notes: 'Befizette az első 120 000 Ft részletet, KRESZ e-learning hozzáférést megkapta.',
    },
  ],
  users: [
    {
      id: 'usr-admin-1',
      username: 'admin',
      fullName: 'Kovács Zoltán (Iskolavezető & Rendszergazda)',
      email: 'admin@autosuli-kepzes.hu',
      role: 'admin',
      passwordHash: 'admin123', // Alapértelmezett jelszó
      active: true,
      avatarColor: 'from-amber-500 to-amber-600',
      createdAt: '2026-01-01T08:00:00.000Z',
      lastLoginAt: '2026-09-23T08:30:00.000Z',
      permissions: {
        canRegisterCourses: true,
        canEditRegistrations: true,
        canPrintContracts: true,
        canCheckoutVehicles: true,
        canEditVehicles: true,
        canManageMaintenance: true,
        canManageLessons: true,
        canOverrideScheduleConflicts: true,
        canManageStudents: true,
        canManageInstructors: true,
        canManageFuel: true,
        canEditCompanyInfo: true,
        canExportImportExcel: true,
        canManageUsers: true,
        canViewAuditLogs: true,
      },
    },
    {
      id: 'usr-clerk-1',
      username: 'ugyvitel',
      fullName: 'Nagy Eszter (Ügyviteli Referens)',
      email: 'eszter.ugyvitel@autosuli-kepzes.hu',
      role: 'clerk',
      passwordHash: 'ugyvitel123', // Alapértelmezett jelszó
      active: true,
      avatarColor: 'from-sky-500 to-blue-600',
      createdAt: '2026-02-15T09:00:00.000Z',
      lastLoginAt: '2026-09-22T14:15:00.000Z',
      permissions: {
        canRegisterCourses: true,
        canEditRegistrations: true,
        canPrintContracts: true,
        canCheckoutVehicles: true,
        canEditVehicles: false,
        canManageMaintenance: false,
        canManageLessons: true,
        canOverrideScheduleConflicts: false,
        canManageStudents: true,
        canManageInstructors: false,
        canManageFuel: true,
        canEditCompanyInfo: false,
        canExportImportExcel: false,
        canManageUsers: false,
        canViewAuditLogs: false,
      },
    },
    {
      id: 'usr-clerk-2',
      username: 'recepcio',
      fullName: 'Tóth Bea (Recepció & Ügyfélszolgálat)',
      email: 'iroda@autosuli-kepzes.hu',
      role: 'clerk',
      passwordHash: 'recepcio123',
      active: true,
      avatarColor: 'from-emerald-500 to-teal-600',
      createdAt: '2026-03-01T10:00:00.000Z',
      lastLoginAt: '2026-09-23T07:45:00.000Z',
      permissions: {
        canRegisterCourses: true,
        canEditRegistrations: false,
        canPrintContracts: true,
        canCheckoutVehicles: true,
        canEditVehicles: false,
        canManageMaintenance: false,
        canManageLessons: true,
        canOverrideScheduleConflicts: false,
        canManageStudents: true,
        canManageInstructors: false,
        canManageFuel: false,
        canEditCompanyInfo: false,
        canExportImportExcel: false,
        canManageUsers: false,
        canViewAuditLogs: false,
      },
    },
  ],
  auditLogs: [
    {
      id: 'log-1',
      timestamp: '2026-09-23T07:45:00.000Z',
      userId: 'usr-clerk-2',
      username: 'recepcio',
      userRole: 'clerk',
      action: 'LOGIN',
      module: 'AUTH',
      details: 'Sikeres bejelentkezés a recepciós terminálról.',
    },
    {
      id: 'log-2',
      timestamp: '2026-09-23T08:10:00.000Z',
      userId: 'usr-clerk-2',
      username: 'recepcio',
      userRole: 'clerk',
      action: 'CREATE',
      module: 'REGISTRATION',
      targetName: 'Horváth Tamás',
      details: 'Új B kategóriás tanfolyam regisztráció (AS-2026/09-001) rögzítve és digitálisan aláírva.',
    },
    {
      id: 'log-3',
      timestamp: '2026-09-23T08:30:00.000Z',
      userId: 'usr-admin-1',
      username: 'admin',
      userRole: 'admin',
      action: 'LOGIN',
      module: 'AUTH',
      details: 'Rendszergazdai bejelentkezés és flotta auditálás.',
    },
  ],
  currentTheme: 'amber-classic',
  appLogo: {
    type: 'icon',
    iconName: 'car',
  },
  isEncrypted: false,
  lastSaved: new Date().toISOString(),
};
